%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 09-Feb-2011 09:56:39

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XScale','log','XMinorTick','on',...
    'XMinorGrid','on',...
    'XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create semilogx
semilogx(freq,imag(Ybranch_dis_tot(:,2)),'Parent',axes1,'Marker','*','LineStyle','none',...
    'DisplayName','658 Real Points');

% Create semilogx
semilogx(transpose(f),imag(Ybranch(:,2)),'Parent',axes1,'LineWidth',2,'DisplayName','Spline');

% Create xlabel
xlabel('f (Hz)');

% Create ylabel
ylabel('Imag(Y12=Y21) (S)');

% Create legend
legend(axes1,'show');